ponylang/lori

examples/echo-server/echo-server.pony

Previously, I had it calling `open()` in the constructor which doesn't
demonstrate that what we really want is to wrap the supplied functions like
`open()` in behaviors for the specific actor.

Provide more realistic API for starting echo server example

---

lori/_test.pony
lori/connection_state.pony
lori/pony_asio.pony
lori/pony_tcp.pony
lori/tcp_connection.pony
lori/tcp_listener.pony

Tests are needed for this but without control over "mute", there isn't
a clear way to test that.
Closes #3

Add backpressure on sending

---

examples/echo-server/echo-server.pony
examples/infinite-ping-pong/infinite-ping-pong.pony
lori/_test.pony
lori/tcp_listener.pony
lori/tcp_listener_actor.pony

Rework Interface/TCPListener relationship

---

examples/echo-server/echo-server.pony
examples/infinite-ping-pong/infinite-ping-pong.pony
lori/_test.pony
lori/auth.pony
lori/tcp_connection.pony
lori/tcp_listener.pony

Make lori capabilities secure

---

lori/pony_tcp.pony

Fix style guide violations in pony_tcp.pony

---

lori/pony_asio.pony
lori/pony_tcp.pony

Localizes the knowledge. Better if they ever change.

Cleans up FFI calls by making them all have `use` directives

---

Makefile
examples/echo-server/echo-server.pony
examples/infinite-ping-pong/infinite-ping-pong.pony
lori/_test.pony
lori/tcp_connection.pony
lori/tcp_connection_actor.pony
lori/tcp_listener_actor.pony

Add `except` support

---

lori/pony_asio.pony
lori/tcp_connection.pony

Add OneShot support to TCPConnection

---

.github/workflows/changelog-bot.yml
.github/workflows/pr.yml
CHANGELOG.md

Add CHANGELOG

---

lori/_test.pony

GitHub actions exposed a bug that wasn't revealed locally or on CircleCI.

Fix ping pong test

---

.github/workflows/announce-a-release.yml
.github/workflows/release-notes-reminder.yml
.github/workflows/release-notes.yml
.github/workflows/release.yml
.github/workflows/start-a-release.yml

Adds automated release process and other release related bots.
Closes #53

Add automated release process

---

.release-notes/62.md
LICENSE

Switch before I accept any contributions.

Change license to BSD

---

.cirrus.yml
.github/workflows/pr.yml

We no longer need nightly for CI to pass.

Switch CI back to going against release

---

.github/workflows/announce-a-release.yml
.github/workflows/breakage-against-ponyc-latest.yml
.github/workflows/changelog-bot.yml
.github/workflows/pr.yml
.github/workflows/prepare-for-a-release.yml
.github/workflows/release-notes-reminder.yml
.github/workflows/release-notes.yml
.github/workflows/release.yml

The ponylang org ones in DockerHub will stop being updated soon.

Switch to using images from GitHub Container Registry

---

.github/workflows/generate-documentation.yml
.github/workflows/release.yml
Makefile

Even if there isn't much there.

Add generation of documentation as part of release

---

.release-notes/keepalive.md
lori/pony_tcp.pony
lori/tcp_connection.pony

Add support for setting TCP keepalive options

---

.release-notes/local-remote.md
lori/pony_tcp.pony
lori/tcp_connection.pony

Add ability to get local and remote names from a socket

---

.release-notes/limit-connections.md
lori/tcp_connection.pony
lori/tcp_connection_actor.pony
lori/tcp_listener.pony
lori/tcp_listener_actor.pony

Allow setting a max connection limit

---

.release-notes/next-release.md
lori/tcp_listener.pony

Make `TCPListener` `host` and `port` private

---

.github/workflows/pr.yml
.github/workflows/update-lib-cache.yml

This should make things much faster.
Closes #111

Cache CI builds of LibreSSL on Windows

---

lori/tcp_connection.pony
lori/tcp_listener.pony

They have been key in finding bugs.

Add additional unreachables

---

.release-notes/happy-eyeballs.md
lori/lifecycle_event_receiver.pony
lori/tcp_connection.pony

Implement Happy Eyeballs

---

.ci-scripts/macOS-configure-networking.bash
.ci-scripts/windows-configure-networking.ps1
.ci-scripts/windows-install-pony-tools.ps1
.github/workflows/pr.yml
.github/workflows/stress-tests.yml
.github/workflows/update-lib-cache.yml
Makefile
corral.json
lori/_test.pony
lori/tcp_connection.pony
lori/tcp_listener.pony
make.ps1
stress-tests/README.md
stress-tests/open-close/README.md
stress-tests/open-close/open-close-stress-test.pony

This commit adds an open/close stress test of Lori. It will run the tests daily and also on PR. It will run for less time on PR.
Windows versions need to be added.
This commit also contains the fixes for issues that the open/close test uncovered.

Add stress test

---

.release-notes/134.md
lori/tcp_connection.pony
lori/tcp_connection_actor.pony
lori/tcp_listener.pony
lori/tcp_listener_actor.pony

Instead of storing an object reference, let's store a more GC friendly token value.:

Fix GC unfriendly connection limiting

---

lori/tcp_connection.pony

IOCP reads and a posix call to "read_again" are the same thing. This commit consolidates them in a single method.

Centralize "queue read" logic

---

lori/tcp_connection.pony

I added some calls to set on the event as well that weren't always done elsewhere. I think these are fine. Will find out.

Consolidate readable/writeable state change calls

---

.release-notes/147.md
corral.json

Update ssl dependency from 1.0.0 to 1.0.1

Update ponylang/ssl dependency
