ponylang/lori

lori/pony_asio.pony, lori/tcp_connection.pony, lori/tcp_listener.pony
Asio is used in the Pony standard library even if I think it should be ASIO.
This change is for consistency with the standard library.
=> Rename PonyASIO to PonyAsio

.circleci/config.yml, lori/pony_tcp.pony, lori/tcp_connection.pony
Pony 0.28.1 fixed a bug where Epoll OneShot events were being done using
edge triggering. That fix, PR#3136
https://github.com/ponylang/ponyc/pull/3136, then proceeded to break
Lori.
The problem? The Pony TCP runtime that Lori currently uses was creating
a one shot event for connections. Lori doesn't currently support one
shot at all.
A recent commit to Pony master
https://github.com/ponylang/ponyc/commit/5f29b1b7edc59d3f1edf797fa86ebf0d4874695f
fixes the issue and allows Lori to work again. This commit brings Lori
up to date with those changes so Lori can work without one shot being
implemented.
=> Allow Lori to work without using ASIO OneShot

lori/tcp_connection.pony
Prior to this commit, when not using expect, Lori would allocate a new
buffer each time a call was made because, we were truncating to the
length of data read rather than chopping off whatever was available.
Thanks to Richard Kallos for pointing this out.
Closes #35
=> Fix performance issue with buffer handling

lori/tcp_connection.pony
It served no real purpose. Would likely end up doing extra allocations
and extra system calls that might not be needed.
=> Remove unneeded TCP read buffer resizing

.circleci/config.yml
Now that lori can build against it again. There was a "bug" in Pony 0.28.x that prevented lori from building.
Closes #37
=> Switch CI back to being against release Ponyc

.cirrus.yml
Runs for every PR. Installs latest release via Homebrew.
Will run debug and release version of Lori code against the release
version of Pony. (There's no debug version of Ponyc released at this
time).
Closes #41
=> Add MacOS CI

.cirrus.yml
At the moment, because there is no prebuilt FreeBSD compiler available, we have to build ponyc before running our tests.
Closes #39
=> Add FreeBSD CI

.release-notes/63.md, lori/tcp_listener.pony
Accept will queue multiple requests together in a single notification
via epoll so you need to keep looking until it returns no additional
results.
=> Fix loss of incoming connections

lori/bit-set.pony
Fewer operations for setting and resetting bits. This is typically how we do it in low-level C and assembler.
=> Bit manipulation optimized.

.cirrus.yml, .github/workflows/breakage-against-ponyc-latest.yml, .github/workflows/pr.yml, Makefile
Adds a new `ci` target that runs both unit-tests and builds the
examples.
Closes #18
=> Only run tests when doing `make test`

.release-notes/79.md, examples/echo-server/echo-server.pony, examples/infinite-ping-pong/infinite-ping-pong.pony, lori/_test.pony, lori/tcp_connection.pony, lori/tcp_connection_actor.pony, lori/tcp_listener.pony, lori/tcp_listener_actor.pony
"on_failure" is very generic and doesn't state what the failure was. When someone is using lori, they will have an "on_failure" callback that could be any number of failures for that actor. Switching the name to "on_connection_failure" should make it considerably more clear.
Closes #78
=> Rename on_failure callback to on_connection_failure

.release-notes/80.md, examples/echo-server/echo-server.pony, examples/infinite-ping-pong/infinite-ping-pong.pony, lori/_test.pony, lori/tcp_connection.pony, lori/tcp_connection_actor.pony, lori/tcp_listener.pony, lori/tcp_listener_actor.pony
There's no need for the callbacks to be public, so I'm making them private. They aren't intended to be called from code outside of Lori and this makes it a bit more specific.
Closes #77
=> Make lori callbacks private

.ci-scripts/freebsd-13-install-nightly-pony-tools.bash, .ci-scripts/freebsd-13-install-release-pony-tools.bash
We don't test on FreeBSD anymore so these aren't needed. CirrusCI became unfree so we have no FreeBSD test environment.
=> Remove FreeBSD pony install tools

.release-notes/accepted.md, lori/tcp_connection.pony, lori/tcp_connection_actor.pony
This allows for setting up of additional information at the time when a connection is accepted. This will be required for implementing things like SSL where the server needs to execute a handshake when the connection is initiated.
=> Add callback for when a server accepts a connection

.release-notes/fix-listener-bug.md, lori/tcp_connection.pony, lori/tcp_listener.pony, lori/tcp_listener_actor.pony
Triggering a callback in the constructor can fail as the enclosing actor won't have had a chance to set its `listener` to our constructed listener.
Any methods called during callbacks from a constructor will be called on the `none()` version of the listener. This is known as "not good".
=> Fix bug in TCPListener

.release-notes/next-release.md, CHANGELOG.md, lori/connection_state.pony, lori/tcp_listener.pony
It is now called `_listening` and is a Bool instead of a union type. `TCPConnectionState` is no longer used and has been removed.
=> Clean up TCPListener's state field

.release-notes/xx.md, examples/echo-server/echo-server.pony, examples/net-ssl-echo-server/net-ssl-echo-server.pony, lori/_test.pony, lori/tcp_listener.pony, lori/tcp_listener_actor.pony
This method is not intended to be called by users of the library, so it should be made private.
=> Make `TCPListenerActor.on_closed` private

examples/echo-server/echo-server.pony, examples/infinite-ping-pong/infinite-ping-pong.pony, examples/net-ssl-echo-server/net-ssl-echo-server.pony, examples/net-ssl-infinite-ping-pong/net-ssl-infinite-ping-pong.pony, lori/_test.pony, lori/net_ssl_connection.pony, stress-tests/open-close/open-close-stress-test.pony
With https://github.com/ponylang/ponyc/issues/4612 fixed in nightlies, these workarounds with expanding the type in various classes is no longer needed.
=> Undo workaround for ponyc bug

.release-notes/132.md, lori/tcp_listener.pony
Previously, it was possible while in a loop on "not windows" to overshoot our listen limit.
=> Fix incorrect listen limit enforcement

.release-notes/133.md, lori/tcp_connection.pony
Make sure we clear pending send data when hard closing. Failure to do so could result in many things not getting garbage collected.
=> Fix memory leak

lori/tcp_connection.pony, lori/tcp_connection_actor.pony, lori/tcp_listener.pony, lori/tcp_listener_actor.pony
This should handle "many many connections have been opened" better for the unlikely scenario that an id was to wrap around while some "early token holders" are still open.
Now, we need to go through not just USize tokens but USize epochs before we hit a conflict with overlapping ids.
=> Add epoch to open connection tokens

.release-notes/limit.md, lori/tcp_listener.pony
Keeping a count across _accept calls for opens we haven't seen yet should be much more accurate. The tricky bit is if we get a close for an open we never saw, we should drop the unseen opens number but if we have seen the connection come back to us then we already have dropped it.
=> Make connection limit more accurate

lori/tcp_connection.pony
We weren't informing the listener if we never connected at all that there was a connection that the listener thought was open that was not in fact open.
=> Inform listener we aren't running on connection failure
